maths=int(input("Enter maths mark="))
physics=int(input("Enter physics mark="))
chemistry=int(input("Enter chemistry mark="))
cs=int(input("Enter CS mark="))
bio=int(input("Enter Biology mark="))
print("maths =",maths)
print("physics=",physics)
print("chemistry=",chemistry)
print("CS=",cs)
print("biology=",bio)